# -*- coding: utf-8 -*-
"""extract.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AseKs0kS1LbmwueX1p1EuKeP7dB5kSHp
"""

import pandas as pd

def resumen_estadistico(df: pd.DataFrame, cols: list[str]) -> pd.DataFrame:
    """
    Devuelve estadísticas descriptivas de columnas seleccionadas.
    """
    return df[cols].describe()


def precio_promedio_por_estrato(df: pd.DataFrame) -> pd.DataFrame:
    """
    Calcula el precio promedio por estrato (1-6).
    """
    df_filtrado = df[df["estrato"].between(1, 6)]
    return (
        df_filtrado
        .groupby("estrato")["precio_total"]
        .mean()
        .reset_index()
    )


def top_barrios_caros(df_prop: pd.DataFrame, df_barrios: pd.DataFrame, n: int = 10) -> pd.DataFrame:
    """
    Devuelve los N barrios con mayor precio promedio.
    """
    merged = df_prop.merge(df_barrios, on="id_barrio", how="left")
    return (
        merged.groupby("nombre")["precio_total"]
        .mean()
        .reset_index()
        .sort_values(by="precio_total", ascending=False)
        .head(n)
    )