# -*- coding: utf-8 -*-
"""load.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K72l6LdnFx_rJgUO-d-dt84zNk9nMdkh
"""

import pandas as pd

def save_to_csv(df: pd.DataFrame, path: str) -> None:
    """
    Guarda un DataFrame en formato CSV.
    """
    df.to_csv(path, index=False)
    print(f"✅ Archivo CSV guardado en: {path}")


def save_to_excel(df: pd.DataFrame, path: str, sheet_name: str = "Sheet1") -> None:
    """
    Guarda un DataFrame en formato Excel.
    """
    df.to_excel(path, sheet_name=sheet_name, index=False)
    print(f"✅ Archivo Excel guardado en: {path} (hoja: {sheet_name})")


def save_to_parquet(df: pd.DataFrame, path: str) -> None:
    """
    Guarda un DataFrame en formato Parquet (óptimo para big data).
    """
    df.to_parquet(path, index=False)
    print(f"✅ Archivo Parquet guardado en: {path}")


def load_from_csv(path: str) -> pd.DataFrame:
    """
    Carga un DataFrame desde un archivo CSV.
    """
    return pd.read_csv(path)


def load_from_excel(path: str, sheet_name: str = "Sheet1") -> pd.DataFrame:
    """
    Carga un DataFrame desde un archivo Excel.
    """
    return pd.read_excel(path, sheet_name=sheet_name)