# -*- coding: utf-8 -*-
"""cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qjR6PFIesBWkv_qwxEN7Ul-I03FowUV4
"""

import pandas as pd

def drop_duplicates(df: pd.DataFrame) -> pd.DataFrame:
    """Elimina filas duplicadas de un DataFrame."""
    return df.drop_duplicates()


def convert_dates(df: pd.DataFrame, col: str) -> pd.DataFrame:
    """Convierte una columna a formato datetime, manejando errores como NaT."""
    df[col] = pd.to_datetime(df[col], errors="coerce")
    return df


def fill_na_with_mean(df: pd.DataFrame, cols: list[str]) -> pd.DataFrame:
    """Rellena valores nulos en columnas numéricas con el promedio."""
    for col in cols:
        if col in df.columns:
            df[col] = df[col].fillna(df[col].mean())
    return df


def remove_outliers_iqr(df: pd.DataFrame, col: str) -> pd.DataFrame:
    """
    Elimina outliers de una columna numérica usando el rango intercuartílico (IQR).
    """
    q1 = df[col].quantile(0.25)
    q3 = df[col].quantile(0.75)
    iqr = q3 - q1
    lower = q1 - 1.5 * iqr
    upper = q3 + 1.5 * iqr

    return df[(df[col] >= lower) & (df[col] <= upper)]


def clean_propiedades(df: pd.DataFrame) -> pd.DataFrame:
    """
    Pipeline de limpieza específico para el DataFrame de propiedades.
    - Elimina duplicados
    - Convierte fechas
    - Imputa nulos en precio_total y area_m2
    - Elimina outliers en precio_total
    """
    df = drop_duplicates(df)
    df = convert_dates(df, "fecha_publicacion")
    df = fill_na_with_mean(df, ["precio_total", "area_m2"])
    df = remove_outliers_iqr(df, "precio_total")
    return df